ae_disc:
  architecture: "ptv3"
  ae_disc_name:
    _target_: FR3D.discriminator.model.modules.discriminator.Discriminator

  in_channels: 4
  order: ["z", "z-trans", "hilbert", "hilbert-trans"]
  stride: [2, 2, 2, 2]
  enc_depths: [2, 2, 2, 2, 2]
  enc_channels: [32, 64, 128, 256, 512]
  enc_num_head: [2, 4, 8, 16, 32]
  enc_patch_size: [1024, 1024, 1024, 1024, 1024]
  dec_depths: [2, 2, 2]
  dec_channels: [128, 128, 256]
  dec_num_head: [8, 8, 16]
  dec_patch_size: [1024, 1024, 1024]
  enable_flash: True
  cls_mode: True
  grid_size: 0.04 # the smaller the grid_size the more grid cells we got. smaller grid size captures more distinct points
  attn_drop: 0.3
  proj_drop: 0.2

  ckpt_path: null
  enc_locdistsnormal: False