ae:
  ae_name:
    _target_: FR3D.denoiser.model.modules.encoder.VQVAE
    
  n_embeddings: 1024
  embedding_dim: 16
  num_point: 100 # 50, 25
  num_dim: 64
  local_decode_pts: 10 # 20, 40
  beta: 0.25

  enc_locdistsnormal: False