data:
  batch_size: 64
  val_batch_size: 64
  num_workers: 10
  data_fn: "bones.{}.txt" #"bones.{}.txt" #"everyday.{}.txt" "artifact.{}.txt"
  data_dir: /home/ssdArray/datasets/Breaking-Bad-Dataset.github.io/data/pc_data_feats/everyday/train/ #/home/datasets/Breaking-Bad-Dataset.synthezised.bones/simpleTibiaHead/pc_data/bones/train/ #/home/datasets/Breaking-Bad-Dataset.github.io/data/pc_data/everyday/train/
  data_val_dir: /home/ssdArray/datasets/Breaking-Bad-Dataset.github.io/data/pc_data_feats/everyday/val/ #/home/datasets/Breaking-Bad-Dataset.synthezised.bones/simpleTibiaHead/pc_data/bones/val/ #/home/datasets/Breaking-Bad-Dataset.github.io/data/pc_data/everyday/val/
  mesh_data_dir: /home/datasets/Breaking-Bad-Dataset.synthezised.bones/advancedTibiaHead/breaking_bad/ #/home/datasets/Breaking-Bad-Dataset.github.io/data/breaking_bad/ #/home/datasets/Breaking-Bad-Dataset.synthezised.bones/simpleTibiaHead/breaking_bad/ #/home/datasets/Breaking-Bad-Dataset.github.io/data/breaking_bad/
  rot_range: -1
  overfit: -1
  data_keys:
    - 'part_ids'
  num_pc_points: 1000 
  min_num_part: 2
  max_num_part: 20
  shuffle_parts: False
  category: all
