title: My Awesome Site
description: "Cederic Aßmann - Technical University Berlin, Learning and Intelligent Systems Lab"
baseurl: "" # leave empty unless serving from a subfolder
url: "https://cederican.github.io/FR3-D"
theme: jekyll-theme-cayman
plugins:
  - jekyll-seo-tag